---
commitizen:
  major_version_zero: true
  name: cz_customize
  tag_format: "v$version"
  version_provider: commitizen
  version_scheme: semver

  customize:
    message_template: |
      {{change_type}}: {{message}}
      
      {{body}}
    
    #schema: "<type>: <body>"
    schema_pattern: "(chore|doc|feat|fix):(\\s.*)"
    #bump_pattern: "^(break|new|fix|hotfix)"
    #commit_parser: "^(?P<change_type>feature|bug fix):\\s(?P<message>.*)?"
    #changelog_pattern: "^(feature|bug fix)?(!)?"
    #change_type_map:
    #  feature: Features
    #  bug fix: Fixes
    #bump_map:
    #  break: MAJOR
    #  new: MINOR
    #  fix: PATCH
    #  hotfix: PATCH
    #change_type_order: ["BREAKING CHANGE", "feat", "fix", "chore", "refactor", "perf"]
    #info_path: cz_customize_info.txt
    info: This is customized info
    questions:
    - type: list
      name: change_type
      choices:
      - value: feat
        name: 'feature: A new feature.'
      - value: fix
        name: 'bug fix: A bug fix.'
      - value: chore
        name: 'chore: A chore task'
      - value: doc
        name: 'doc: A change to the documentation'      
      message: Select the type of change you are committing
    - type: input
      name: message
      message: Commit Message.
    - type: input
      name: body
      message: Commit Message Body.
    