---
commitizen:
  customize:
    info: This is customized info
    message_template: '{{change_type}}: {{message}}


      {{body}}

      '
    questions:
    - choices:
      - name: 'feature: A new feature.'
        value: feat
      - name: 'bug fix: A bug fix.'
        value: fix
      - name: 'chore: A chore task'
        value: chore
      - name: 'doc: A change to the documentation'
        value: doc
      message: Select the type of change you are committing
      name: change_type
      type: list
    - message: Commit Message.
      name: message
      type: input
    - message: Commit Message Body.
      name: body
      type: input
    schema_pattern: (bump|chore|doc|feat|fix):(\s.*)
  major_version_zero: true
  name: cz_customize
  tag_format: v$version
  version: 0.1.0
  version_provider: commitizen
  version_scheme: semver
